//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCPaymentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRequest
    {
        public Nullable<double> Vendor_Code { get; set; }
        public double PaymentReqId { get; set; }
        public Nullable<double> PR_Status { get; set; }
        public Nullable<double> Vendor_Invoice__ { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<System.DateTime> Invoice_Submitted_Date { get; set; }
        public string Service_Period { get; set; }
        public Nullable<double> Invoice_Amount { get; set; }
    }
}
