//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCPaymentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRNewRequest
    {
        public double PaymentReqId { get; set; }
        public Nullable<double> VendorCode { get; set; }
        public string FMSRegistration { get; set; }
        public string ContractPIN { get; set; }
        public Nullable<System.DateTime> MHYNumberId { get; set; }
        public Nullable<System.DateTime> ServiceFromDate { get; set; }
        public Nullable<System.DateTime> ServiceToDate { get; set; }
    }
}
