//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NYCPaymentPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRSearch
    {
        public double PaymentReqId { get; set; }
        public Nullable<double> Vendor_Code { get; set; }
        public Nullable<double> PaymentReqId1 { get; set; }
        public Nullable<double> PR_Status { get; set; }
        public string FMS_Registration { get; set; }
        public string ContractPIN { get; set; }
        public Nullable<double> Vendor_Invoice__ { get; set; }
        public Nullable<double> Invoice_Amount { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<System.DateTime> Invoice_Submission_Date { get; set; }
        public Nullable<System.DateTime> ServiceFromDate { get; set; }
        public Nullable<double> MHYNumberId { get; set; }
    }
}
